import type{Metadata} from "next";
import {Inter} from "next/font/google";

import { ClerkProvider,SignInButton,SignedIn,SignedOut,UserButton } from "@clerk/nextjs";
import React from "react";
import { shadesOfPurple, neobrutalism } from "@clerk/themes";
import styles from "./page.module.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children,
}:Readonly<{
children:React.ReactNode;
}>){
    return(
        <ClerkProvider  appearance={{ 
            baseTheme: [ shadesOfPurple, neobrutalism] ,  
            variables:{colorText:'red',
            }
        }}
            >
            <html lang="en">
            <body className={inter.className}>
                <header className="flex justify-between p-5">
                    <SignedOut>
                    <div>
                    <SignInButton>
                     <button className={styles.customButton}>Sign in</button>
                     </SignInButton>
                        </div>
                    </SignedOut>
                    <SignedIn>
                        <UserButton showName />
                    </SignedIn>
                </header>
                <main>
                    {children}
                </main>
            </body>
            </html>
        </ClerkProvider>
    );
}